/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package game;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF19URCVIwL6FU= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF19URCVIwL6FU= >>
// ----------- >>
public class Animal extends Species {
    // ----------- << attribute.annotations@AAAAAAF19VJzIwkCoFQ= >>
    // ----------- >>
    private int strenght;

    // ----------- << attribute.annotations@AAAAAAF2JCJRPL6Q2Sg= >>
    // ----------- >>
    private byte typeOfAnimals;

    // ----------- << attribute.annotations@AAAAAAF2JCVKsMY29bI= >>
    // ----------- >>
    private int energyGiven;

    // ----------- << attribute.annotations@AAAAAAF2JCbK5cm6j8M= >>
    // ----------- >>
    private int energyNeed;

    // ----------- << attribute.annotations@AAAAAAF19UYal5BEY8M= >>
    // ----------- >>
    private Species ;

    protected int getStrenght() {
        return strenght;
    }

    protected byte getTypeOfAnimals() {
        return typeOfAnimals;
    }

    protected int getEnergyGiven() {
        return energyGiven;
    }

    protected int getEnergyNeed() {
        return energyNeed;
    }

    public Species get() {
        return ;
    }

    protected void setStrenght(int strenght) {
        this.strenght = strenght;
    }

    protected void setTypeOfAnimals(byte typeOfAnimals) {
        this.typeOfAnimals = typeOfAnimals;
    }

    protected void setEnergyGiven(int energyGiven) {
        this.energyGiven = energyGiven;
    }

    protected void setEnergyNeed(int energyNeed) {
        this.energyNeed = energyNeed;
    }

    public void set(Species ) {
        this. = ;
    }

    public void link(Species _) {
        set(_);
    }

    public void unlink() {
        set(null);
    }

    // ----------- << method.annotations@AAAAAAF2JDqVrDUX1aA= >>
    // ----------- >>
    public Animal() {
    // ----------- << method.body@AAAAAAF2JDqVrDUX1aA= >>
    // ----------- >>
    }
    /**
    * @param animal
    */

    // ----------- << method.annotations@AAAAAAF2JBsdXqdbVc8= >>
    // ----------- >>
    public void eat(Animal animal) {
    // ----------- << method.body@AAAAAAF2JBsdXqdbVc8= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF19URCVIwL6FU= >>
// ----------- >>
}