/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package game;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF19UbwR5aJFjI= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF19UbwR5aJFjI= >>
// ----------- >>
public class AquaticMammal extends Animal {
    // ----------- << attribute.annotations@AAAAAAF19Ucq2pjfZHU= >>
    // ----------- >>
    private Mammal ;

    // ----------- << attribute.annotations@AAAAAAF19Uk8qZ7NwSI= >>
    // ----------- >>
    private AquaticAnimal ;

    // ----------- << attribute.annotations@AAAAAAF19UxYh79aKB0= >>
    // ----------- >>
    private Animal ;

    public Mammal get() {
        return ;
    }

    public AquaticAnimal get() {
        return ;
    }

    public Animal get() {
        return ;
    }

    public void set(Mammal ) {
        this. = ;
    }

    public void set(AquaticAnimal ) {
        this. = ;
    }

    public void set(Animal ) {
        this. = ;
    }

    public void link(Mammal _) {
        set(_);
    }

    public void link(AquaticAnimal _) {
        set(_);
    }

    public void link(Animal _) {
        set(_);
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        set(null);
    }

    // ----------- << method.annotations@AAAAAAF2JD7JnWcJWrs= >>
    // ----------- >>
    public AquaticMammal() {
    // ----------- << method.body@AAAAAAF2JD7JnWcJWrs= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF19UbwR5aJFjI= >>
// ----------- >>
}