/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package game;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF19XyP3I2wJ94= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF19XyP3I2wJ94= >>
// ----------- >>
public class Atmosphere {
    // ----------- << attribute.annotations@AAAAAAF19XzDEZKCef0= >>
    // ----------- >>
    private PlanetData ;

    // ----------- << attribute.annotations@AAAAAAF19X3KrsXmSpI= >>
    // ----------- >>
    private Gaz ;

    // ----------- << attribute.annotations@AAAAAAF19X3hpcqpq68= >>
    // ----------- >>
    private Gaz ;

    public PlanetData get() {
        return ;
    }

    public Gaz get() {
        return ;
    }

    public Gaz get() {
        return ;
    }

    public void set(PlanetData ) {
        this. = ;
    }

    public void set(Gaz ) {
        this. = ;
    }

    public void set(Gaz ) {
        this. = ;
    }

    public void link(PlanetData _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Gaz _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Gaz _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF2JEEpPYjXV34= >>
    // ----------- >>
    public Atmosphere() {
    // ----------- << method.body@AAAAAAF2JEEpPYjXV34= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF19XyP3I2wJ94= >>
// ----------- >>
}