/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package game;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF2JAiEYzTYfjk= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF2JAiEYzTYfjk= >>
// ----------- >>
public class City {
    // ----------- << attribute.annotations@AAAAAAF2JAlKvTv6iag= >>
    // ----------- >>
    private boolean dormitory;

    // ----------- << attribute.annotations@AAAAAAF2JAsUDU3D0H4= >>
    // ----------- >>
    private boolean oxygenSupply;

    // ----------- << attribute.annotations@AAAAAAF2JAshCU65P4w= >>
    // ----------- >>
    private boolean energyPlant;

    // ----------- << attribute.annotations@AAAAAAF2JBBCs3Pv7TU= >>
    // ----------- >>
    private int nbFactory;

    // ----------- << attribute.annotations@AAAAAAF2JER4n6QEyYs= >>
    // ----------- >>
    private String cityName;

    // ----------- << attribute.annotations@AAAAAAF2JAulfFQNGrE= >>
    // ----------- >>
    private Planet ;

    // ----------- << attribute.annotations@AAAAAAF2JA3CfWooqzI= >>
    // ----------- >>
    private Factory ;

    private boolean isDormitory() {
        return dormitory;
    }

    private boolean isOxygenSupply() {
        return oxygenSupply;
    }

    private boolean isEnergyPlant() {
        return energyPlant;
    }

    private int getNbFactory() {
        return nbFactory;
    }

    private String getCityName() {
        return cityName;
    }

    public Planet get() {
        return ;
    }

    public Factory get() {
        return ;
    }

    private void setDormitory(boolean dormitory) {
        this.dormitory = dormitory;
    }

    private void setOxygenSupply(boolean oxygenSupply) {
        this.oxygenSupply = oxygenSupply;
    }

    private void setEnergyPlant(boolean energyPlant) {
        this.energyPlant = energyPlant;
    }

    private void setNbFactory(int nbFactory) {
        this.nbFactory = nbFactory;
    }

    private void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public void set(Planet ) {
        this. = ;
    }

    public void set(Factory ) {
        this. = ;
    }

    public void link(Planet _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Factory _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF2JDKhMAD5wRs= >>
    // ----------- >>
    public double produceRessources() {
    // ----------- << method.body@AAAAAAF2JDKhMAD5wRs= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF2JD3yPF2cHV0= >>
    // ----------- >>
    public City() {
    // ----------- << method.body@AAAAAAF2JD3yPF2cHV0= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF2JAiEYzTYfjk= >>
// ----------- >>
}