/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package game;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF2JA2VDGdGaO8= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF2JA2VDGdGaO8= >>
// ----------- >>
public class Factory {
    // ----------- << attribute.annotations@AAAAAAF2JA3wOGznwvk= >>
    // ----------- >>
    private void Attribute1;

    // ----------- << attribute.annotations@AAAAAAF2JA37JG4NtVI= >>
    // ----------- >>
    private void Attribute2;

    // ----------- << attribute.annotations@AAAAAAF2JA3CfWopv4Q= >>
    // ----------- >>
    private City ;

    private void getAttribute1() {
        return Attribute1;
    }

    private void getAttribute2() {
        return Attribute2;
    }

    public City get() {
        return ;
    }

    private void setAttribute1(void Attribute1) {
        this.Attribute1 = Attribute1;
    }

    private void setAttribute2(void Attribute2) {
        this.Attribute2 = Attribute2;
    }

    public void set(City ) {
        this. = ;
    }

    public void link(City _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

// ----------- << class.extras@AAAAAAF2JA2VDGdGaO8= >>
// ----------- >>
}