/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package game;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF19UZCDpGUiaE= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF19UZCDpGUiaE= >>
// ----------- >>
public class Fish extends Fish,Animal {
    // ----------- << attribute.annotations@AAAAAAF19UbPRpS0/dA= >>
    // ----------- >>
    private Invertebrate ;

    // ----------- << attribute.annotations@AAAAAAF19UbZlpVC78M= >>
    // ----------- >>
    private Vertebrate ;

    // ----------- << attribute.annotations@AAAAAAF19UpgzLM74Xs= >>
    // ----------- >>
    private AquaticAnimal ;

    // ----------- << attribute.annotations@AAAAAAF19UxNmr6fHqs= >>
    // ----------- >>
    private Animal ;

    public Invertebrate get() {
        return ;
    }

    public Vertebrate get() {
        return ;
    }

    public AquaticAnimal get() {
        return ;
    }

    public Animal get() {
        return ;
    }

    public void set(Invertebrate ) {
        this. = ;
    }

    public void set(Vertebrate ) {
        this. = ;
    }

    public void set(AquaticAnimal ) {
        this. = ;
    }

    public void set(Animal ) {
        this. = ;
    }

    public void link(Invertebrate _) {
        set(_);
    }

    public void link(Vertebrate _) {
        set(_);
    }

    public void link(AquaticAnimal _) {
        set(_);
    }

    public void link(Animal _) {
        set(_);
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        set(null);
    }

// ----------- << class.extras@AAAAAAF19UZCDpGUiaE= >>
// ----------- >>
}