/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package game;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF19XR5zgmDbeY= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF19XR5zgmDbeY= >>
// ----------- >>
public class Game {
    // ----------- << attribute.annotations@AAAAAAF19XnDp2aR570= >>
    // ----------- >>
    private double money;

    // ----------- << attribute.annotations@AAAAAAF2JDX1mRUBkFs= >>
    // ----------- >>
    private double temperature;

    // ----------- << attribute.annotations@AAAAAAF2JDYGhhYPMOo= >>
    // ----------- >>
    private double pression;

    // ----------- << attribute.annotations@AAAAAAF2JDYQkhcdTYg= >>
    // ----------- >>
    private double oxygen;

    // ----------- << attribute.annotations@AAAAAAF2JDYm2RgrhM8= >>
    // ----------- >>
    private double biomass;

    // ----------- << attribute.annotations@AAAAAAF2JDggVSWtHQw= >>
    // ----------- >>
    private double water;

    // ----------- << attribute.annotations@AAAAAAF19XgwzkRgaQg= >>
    // ----------- >>
    private Planet ;

    // ----------- << attribute.annotations@AAAAAAF19XVBmBtEuCU= >>
    // ----------- >>
    private Mission ;

    // ----------- << attribute.annotations@AAAAAAF19XieCUppIoY= >>
    // ----------- >>
    private Money ;

    // ----------- << attribute.annotations@AAAAAAF19Xo3/XGbb5Q= >>
    // ----------- >>
    private Settings ;

    private double getMoney() {
        return money;
    }

    private double getTemperature() {
        return temperature;
    }

    private double getPression() {
        return pression;
    }

    private double getOxygen() {
        return oxygen;
    }

    private double getBiomass() {
        return biomass;
    }

    private double getWater() {
        return water;
    }

    public Planet get() {
        return ;
    }

    public Mission get() {
        return ;
    }

    public Money get() {
        return ;
    }

    public Settings get() {
        return ;
    }

    private void setMoney(double money) {
        this.money = money;
    }

    private void setTemperature(double temperature) {
        this.temperature = temperature;
    }

    private void setPression(double pression) {
        this.pression = pression;
    }

    private void setOxygen(double oxygen) {
        this.oxygen = oxygen;
    }

    private void setBiomass(double biomass) {
        this.biomass = biomass;
    }

    private void setWater(double water) {
        this.water = water;
    }

    public void set(Planet ) {
        this. = ;
    }

    public void set(Mission ) {
        this. = ;
    }

    public void set(Money ) {
        this. = ;
    }

    public void set(Settings ) {
        this. = ;
    }

    public void link(Planet _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Mission _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Money _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Settings _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF2JECYWH/wKAs= >>
    // ----------- >>
    public Game() {
    // ----------- << method.body@AAAAAAF2JECYWH/wKAs= >>
    // ----------- >>
    }
    /**
    * @param newMoney
    */

    // ----------- << method.annotations@AAAAAAF2JEHO+ZLnAek= >>
    // ----------- >>
    public void setMoney(double newMoney) {
    // ----------- << method.body@AAAAAAF2JEHO+ZLnAek= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF19XR5zgmDbeY= >>
// ----------- >>
}