/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package game;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF19X1dBLpfJkI= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF19X1dBLpfJkI= >>
// ----------- >>
public class Gaz {
    // ----------- << attribute.annotations@AAAAAAF19X2Qkb/v0GA= >>
    // ----------- >>
    private double proportion;

    // ----------- << attribute.annotations@AAAAAAF19YGoDfZEtKo= >>
    // ----------- >>
    private String name;

    // ----------- << attribute.annotations@AAAAAAF19X3KrsXnVOw= >>
    // ----------- >>
    private Atmosphere ;

    // ----------- << attribute.annotations@AAAAAAF19X3hpcqqf1I= >>
    // ----------- >>
    private Atmosphere ;

    // ----------- << attribute.annotations@AAAAAAF19X7dz+JNh10= >>
    // ----------- >>
    private Oxygen ;

    private double getProportion() {
        return proportion;
    }

    private String getName() {
        return name;
    }

    public Atmosphere get() {
        return ;
    }

    public Atmosphere get() {
        return ;
    }

    public Oxygen get() {
        return ;
    }

    private void setProportion(double proportion) {
        this.proportion = proportion;
    }

    private void setName(String name) {
        this.name = name;
    }

    public void set(Atmosphere ) {
        this. = ;
    }

    public void set(Atmosphere ) {
        this. = ;
    }

    public void set(Oxygen ) {
        this. = ;
    }

    public void link(Atmosphere _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Atmosphere _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Oxygen _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF2JEGcV4/jSGo= >>
    // ----------- >>
    public Gaz() {
    // ----------- << method.body@AAAAAAF2JEGcV4/jSGo= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF19X1dBLpfJkI= >>
// ----------- >>
}