/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package game;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF19U1cIetHl6s= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF19U1cIetHl6s= >>
// ----------- >>
public class Human extends Mammal {
    // ----------- << attribute.annotations@AAAAAAF19U126Oz6C74= >>
    // ----------- >>
    private Mammal ;

    public Mammal get() {
        return ;
    }

    public void set(Mammal ) {
        this. = ;
    }

    public void link(Mammal _) {
        set(_);
    }

    public void unlink() {
        set(null);
    }

    // ----------- << method.annotations@AAAAAAF2JDvd9EG2AWo= >>
    // ----------- >>
    public Human() {
    // ----------- << method.body@AAAAAAF2JDvd9EG2AWo= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF19U1cIetHl6s= >>
// ----------- >>
}