/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package game;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF19WN+bbsItsQ= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF19WN+bbsItsQ= >>
// ----------- >>
public class Insect extends Animal {
    // ----------- << method.annotations@AAAAAAF2JD7/Tmj/6FE= >>
    // ----------- >>
    public Insect() {
    // ----------- << method.body@AAAAAAF2JD7/Tmj/6FE= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF19WN+bbsItsQ= >>
// ----------- >>
}