/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package game;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF19UVkZY26c8Y= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF19UVkZY26c8Y= >>
// ----------- >>
public class Invertebrate {
    // ----------- << attribute.annotations@AAAAAAF19UXtg49Fd34= >>
    // ----------- >>
    private Animal ;

    public Animal get() {
        return ;
    }

    public void set(Animal ) {
        this. = ;
    }

    public void link(Animal _) {
        set(_);
    }

    public void unlink() {
        set(null);
    }

// ----------- << class.extras@AAAAAAF19UVkZY26c8Y= >>
// ----------- >>
}