/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package game;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF19UZHUpIIkgE= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF19UZHUpIIkgE= >>
// ----------- >>
public class Mammal extends Animal {
    // ----------- << attribute.annotations@AAAAAAF19UbgRJXfPXE= >>
    // ----------- >>
    private Vertebrate ;

    // ----------- << attribute.annotations@AAAAAAF19UyAqsOUZ04= >>
    // ----------- >>
    private Animal ;

    public Vertebrate get() {
        return ;
    }

    public Animal get() {
        return ;
    }

    public void set(Vertebrate ) {
        this. = ;
    }

    public void set(Animal ) {
        this. = ;
    }

    public void link(Vertebrate _) {
        set(_);
    }

    public void link(Animal _) {
        set(_);
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        set(null);
    }

    // ----------- << method.annotations@AAAAAAF2JDuPsj2pF4g= >>
    // ----------- >>
    public Mammal() {
    // ----------- << method.body@AAAAAAF2JDuPsj2pF4g= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF19UZHUpIIkgE= >>
// ----------- >>
}