/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package game;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF19XS00BCbwGs= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF19XS00BCbwGs= >>
// ----------- >>
public class Mission extends Mission {
    // ----------- << attribute.annotations@AAAAAAF19XWInB4LN6o= >>
    // ----------- >>
    private double reward;

    // ----------- << attribute.annotations@AAAAAAF19Xc+JzSVGhQ= >>
    // ----------- >>
    private String title;

    // ----------- << attribute.annotations@AAAAAAF19XenyDlNYGw= >>
    // ----------- >>
    private String description;

    // ----------- << attribute.annotations@AAAAAAF19XfkKT3IBxg= >>
    // ----------- >>
    private boolean achieved;

    // ----------- << attribute.annotations@AAAAAAF19XVBmBtFnCY= >>
    // ----------- >>
    private Game ;

    private double getReward() {
        return reward;
    }

    private String getTitle() {
        return title;
    }

    private String getDescription() {
        return description;
    }

    private boolean isAchieved() {
        return achieved;
    }

    public Game get() {
        return ;
    }

    private void setReward(double reward) {
        this.reward = reward;
    }

    private void setTitle(String title) {
        this.title = title;
    }

    private void setDescription(String description) {
        this.description = description;
    }

    private void setAchieved(boolean achieved) {
        this.achieved = achieved;
    }

    public void set(Game ) {
        this. = ;
    }

    public void link(Game _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF2JEDTQIO78Rc= >>
    // ----------- >>
    public Mission() {
    // ----------- << method.body@AAAAAAF2JEDTQIO78Rc= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF2JEXygatq8PU= >>
    // ----------- >>
    public void missionAchieved() {
    // ----------- << method.body@AAAAAAF2JEXygatq8PU= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF19XS00BCbwGs= >>
// ----------- >>
}