/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package game;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF19XhpGUZME8c= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF19XhpGUZME8c= >>
// ----------- >>
public class Money {
    // ----------- << attribute.annotations@AAAAAAF19Xj6ymFFG3g= >>
    // ----------- >>
    private void Attribute1;

    // ----------- << attribute.annotations@AAAAAAF19XieCUpqeEY= >>
    // ----------- >>
    private Game ;

    public void getAttribute1() {
        return Attribute1;
    }

    public Game get() {
        return ;
    }

    public void setAttribute1(void Attribute1) {
        this.Attribute1 = Attribute1;
    }

    public void set(Game ) {
        this. = ;
    }

    public void link(Game _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

// ----------- << class.extras@AAAAAAF19XhpGUZME8c= >>
// ----------- >>
}