/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package game;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF19X7L5+A//5w= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF19X7L5+A//5w= >>
// ----------- >>
public class Oxygen {
    // ----------- << attribute.annotations@AAAAAAF19X7dz+JO+84= >>
    // ----------- >>
    private Gaz ;

    // ----------- << attribute.annotations@AAAAAAF19X7xROY50RU= >>
    // ----------- >>
    private Gaz ;

    public Gaz get() {
        return ;
    }

    public Gaz get() {
        return ;
    }

    public void set(Gaz ) {
        this. = ;
    }

    public void set(Gaz ) {
        this. = ;
    }

    public void link(Gaz _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Gaz _) {
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        set(null);
    }

// ----------- << class.extras@AAAAAAF19X7L5+A//5w= >>
// ----------- >>
}