/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package game;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF19UHZT4kk7LI= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF19UHZT4kk7LI= >>
// ----------- >>
public class PlanetData {
    // ----------- << attribute.annotations@AAAAAAF19Un54KhDcaU= >>
    // ----------- >>
    private Planet ;

    // ----------- << attribute.annotations@AAAAAAF19UlxFJ+lk5Y= >>
    // ----------- >>
    private Weather ;

    // ----------- << attribute.annotations@AAAAAAF19XzDEZKBviY= >>
    // ----------- >>
    private Atmosphere ;

    public Planet get() {
        return ;
    }

    public Weather get() {
        return ;
    }

    public Atmosphere get() {
        return ;
    }

    public void set(Planet ) {
        this. = ;
    }

    public void set(Weather ) {
        this. = ;
    }

    public void set(Atmosphere ) {
        this. = ;
    }

    public void link(Planet _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Weather _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Atmosphere _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF2JEDtyYVv7/Q= >>
    // ----------- >>
    public PlanetData() {
    // ----------- << method.body@AAAAAAF2JEDtyYVv7/Q= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF19UHZT4kk7LI= >>
// ----------- >>
}