/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package game;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF19UFaEIiHvu8= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF19UFaEIiHvu8= >>
// ----------- >>
public class Planet {
    // ----------- << attribute.annotations@AAAAAAF19XgwzkRhIt0= >>
    // ----------- >>
    private Game ;

    // ----------- << attribute.annotations@AAAAAAF19UGs64jcQao= >>
    // ----------- >>
    private Species ;

    // ----------- << attribute.annotations@AAAAAAF19ULTYorBQYs= >>
    // ----------- >>
    private Species ;

    // ----------- << attribute.annotations@AAAAAAF19Un54KhCJP8= >>
    // ----------- >>
    private PlanetData ;

    // ----------- << attribute.annotations@AAAAAAF2JAulfFQMYm0= >>
    // ----------- >>
    private City ;

    public Game get() {
        return ;
    }

    public Species get() {
        return ;
    }

    public Species get() {
        return ;
    }

    public PlanetData get() {
        return ;
    }

    public City get() {
        return ;
    }

    public void set(Game ) {
        this. = ;
    }

    public void set(Species ) {
        this. = ;
    }

    public void set(Species ) {
        this. = ;
    }

    public void set(PlanetData ) {
        this. = ;
    }

    public void set(City ) {
        this. = ;
    }

    public void link(Game _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Species _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Species _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(PlanetData _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(City _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF2JD4FUl+4ofY= >>
    // ----------- >>
    public Planet() {
    // ----------- << method.body@AAAAAAF2JD4FUl+4ofY= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF19UFaEIiHvu8= >>
// ----------- >>
}