/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package game;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF19XoNQW1+TEs= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF19XoNQW1+TEs= >>
// ----------- >>
public class Settings {
    // ----------- << attribute.annotations@AAAAAAF19XpO1HPedrQ= >>
    // ----------- >>
    private double moneyStart;

    // ----------- << attribute.annotations@AAAAAAF19YdTJDbFUps= >>
    // ----------- >>
    private double temperatureStart;

    // ----------- << attribute.annotations@AAAAAAF19YdvTTnCa2o= >>
    // ----------- >>
    private double pressionStart;

    // ----------- << attribute.annotations@AAAAAAF19Yd5bjvwx00= >>
    // ----------- >>
    private double oxygenStart;

    // ----------- << attribute.annotations@AAAAAAF19YpkWEl0uBI= >>
    // ----------- >>
    private double biomassStart;

    // ----------- << attribute.annotations@AAAAAAF19YqW4E3LOIY= >>
    // ----------- >>
    private double waterStart;

    // ----------- << attribute.annotations@AAAAAAF19Xo3/XGcI1A= >>
    // ----------- >>
    private Game ;

    private double getMoneyStart() {
        return moneyStart;
    }

    private double getTemperatureStart() {
        return temperatureStart;
    }

    private double getPressionStart() {
        return pressionStart;
    }

    private double getOxygenStart() {
        return oxygenStart;
    }

    private double getBiomassStart() {
        return biomassStart;
    }

    private double getWaterStart() {
        return waterStart;
    }

    public Game get() {
        return ;
    }

    private void setMoneyStart(double moneyStart) {
        this.moneyStart = moneyStart;
    }

    private void setTemperatureStart(double temperatureStart) {
        this.temperatureStart = temperatureStart;
    }

    private void setPressionStart(double pressionStart) {
        this.pressionStart = pressionStart;
    }

    private void setOxygenStart(double oxygenStart) {
        this.oxygenStart = oxygenStart;
    }

    private void setBiomassStart(double biomassStart) {
        this.biomassStart = biomassStart;
    }

    private void setWaterStart(double waterStart) {
        this.waterStart = waterStart;
    }

    public void set(Game ) {
        this. = ;
    }

    public void link(Game _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF19Y1Yqnx3C/Y= >>
    // ----------- >>
    public void bool success() {
    // ----------- << method.body@AAAAAAF19Y1Yqnx3C/Y= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF2JECzcoGk7w8= >>
    // ----------- >>
    public Settings() {
    // ----------- << method.body@AAAAAAF2JECzcoGk7w8= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF19XoNQW1+TEs= >>
// ----------- >>
}