/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package game;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF19V0ue0ifryQ= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF19V0ue0ifryQ= >>
// ----------- >>
public class SingleCellOrganism extends Fish {
    // ----------- << attribute.annotations@AAAAAAF19V3pqlq7mk8= >>
    // ----------- >>
    private Fish ;

    public Fish get() {
        return ;
    }

    public void set(Fish ) {
        this. = ;
    }

    public void link(Fish _) {
        set(_);
    }

    public void unlink() {
        set(null);
    }

    // ----------- << method.annotations@AAAAAAF2JEAVjHjH24M= >>
    // ----------- >>
    public SingleCellOrganism() {
    // ----------- << method.body@AAAAAAF2JEAVjHjH24M= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF19V0ue0ifryQ= >>
// ----------- >>
}