/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package game;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF19YTN1xFWZjg= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF19YTN1xFWZjg= >>
// ----------- >>
public class Temperature {
    // ----------- << attribute.annotations@AAAAAAF19YUQzBruHmY= >>
    // ----------- >>
    private void double upperLimit;

    // ----------- << attribute.annotations@AAAAAAF19YVf1yLIUiM= >>
    // ----------- >>
    private void double lowerLimit;

    // ----------- << attribute.annotations@AAAAAAF19YT6khYnV6w= >>
    // ----------- >>
    private Weather ;

    // ----------- << attribute.annotations@AAAAAAF19ZKgntr4KQQ= >>
    // ----------- >>
    private Weather ;

    // ----------- << attribute.annotations@AAAAAAF19ZK4wN68cdo= >>
    // ----------- >>
    private Weather ;

    public void getDouble upperLimit() {
        return double upperLimit;
    }

    public void getDouble lowerLimit() {
        return double lowerLimit;
    }

    public Weather get() {
        return ;
    }

    public Weather get() {
        return ;
    }

    public Weather get() {
        return ;
    }

    public void setDouble upperLimit(void double upperLimit) {
        this.double upperLimit = double upperLimit;
    }

    public void setDouble lowerLimit(void double lowerLimit) {
        this.double lowerLimit = double lowerLimit;
    }

    public void set(Weather ) {
        this. = ;
    }

    public void set(Weather ) {
        this. = ;
    }

    public void set(Weather ) {
        this. = ;
    }

    public void link(Weather _) {
        set(_);
    }

    public void link(Weather _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Weather _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF2JEFTqItyk50= >>
    // ----------- >>
    public Temperature() {
    // ----------- << method.body@AAAAAAF2JEFTqItyk50= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF19YTN1xFWZjg= >>
// ----------- >>
}