/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package game;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF19WDp+ZvvmTc= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF19WDp+ZvvmTc= >>
// ----------- >>
public class Tree extends Vegetal {
    // ----------- << attribute.annotations@AAAAAAF19WGQX7DL/i4= >>
    // ----------- >>
    private Vegetal ;

    public Vegetal get() {
        return ;
    }

    public void set(Vegetal ) {
        this. = ;
    }

    public void link(Vegetal _) {
        set(_);
    }

    public void unlink() {
        set(null);
    }

    // ----------- << method.annotations@AAAAAAF2JDz7VVHCgW8= >>
    // ----------- >>
    public Tree() {
    // ----------- << method.body@AAAAAAF2JDz7VVHCgW8= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF19WDp+ZvvmTc= >>
// ----------- >>
}