/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package game;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF19USHPYxudMY= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF19USHPYxudMY= >>
// ----------- >>
public class Vegetal extends Species {
    // ----------- << attribute.annotations@AAAAAAF2JCr6vNMrLC8= >>
    // ----------- >>
    private double oxygenGiven;

    // ----------- << attribute.annotations@AAAAAAF2JC1KveChaHA= >>
    // ----------- >>
    private double carbonDioxydeAbsorbed;

    // ----------- << attribute.annotations@AAAAAAF19UYp1pDMxok= >>
    // ----------- >>
    private Species ;

    protected double getOxygenGiven() {
        return oxygenGiven;
    }

    protected double getCarbonDioxydeAbsorbed() {
        return carbonDioxydeAbsorbed;
    }

    public Species get() {
        return ;
    }

    protected void setOxygenGiven(double oxygenGiven) {
        this.oxygenGiven = oxygenGiven;
    }

    protected void setCarbonDioxydeAbsorbed(double carbonDioxydeAbsorbed) {
        this.carbonDioxydeAbsorbed = carbonDioxydeAbsorbed;
    }

    public void set(Species ) {
        this. = ;
    }

    public void link(Species _) {
        set(_);
    }

    public void unlink() {
        set(null);
    }

    // ----------- << method.annotations@AAAAAAF2JDx/bkrZEuU= >>
    // ----------- >>
    public Vegetal() {
    // ----------- << method.body@AAAAAAF2JDx/bkrZEuU= >>
    // ----------- >>
    }
    /**
    * @param vegetal
    */

    // ----------- << method.annotations@AAAAAAF2JC5U/Oa8exY= >>
    // ----------- >>
    public void reproduce(Vegetal vegetal) {
    // ----------- << method.body@AAAAAAF2JC5U/Oa8exY= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF19USHPYxudMY= >>
// ----------- >>
}