/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package game;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF19UPJ3IsVqWs= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF19UPJ3IsVqWs= >>
// ----------- >>
public class Weather {
    // ----------- << attribute.annotations@AAAAAAF19YMMt/3x7Wg= >>
    // ----------- >>
    private void double temperature;

    // ----------- << attribute.annotations@AAAAAAF19UlxFJ+mZWE= >>
    // ----------- >>
    private PlanetData ;

    // ----------- << attribute.annotations@AAAAAAF19UmhFaCN5/0= >>
    // ----------- >>
    private Temperature ;

    // ----------- << attribute.annotations@AAAAAAF19UnYO6NI7xk= >>
    // ----------- >>
    private Humidity ;

    // ----------- << attribute.annotations@AAAAAAF19ZMaZeJx6lA= >>
    // ----------- >>
    private Pression ;

    // ----------- << attribute.annotations@AAAAAAF19ZKgntr3lbE= >>
    // ----------- >>
    private Temperature ;

    // ----------- << attribute.annotations@AAAAAAF19ZK4wN67ENk= >>
    // ----------- >>
    private Temperature ;

    public void getDouble temperature() {
        return double temperature;
    }

    public PlanetData get() {
        return ;
    }

    public Temperature get() {
        return ;
    }

    public Humidity get() {
        return ;
    }

    public Pression get() {
        return ;
    }

    public Temperature get() {
        return ;
    }

    public Temperature get() {
        return ;
    }

    public void setDouble temperature(void double temperature) {
        this.double temperature = double temperature;
    }

    public void set(PlanetData ) {
        this. = ;
    }

    public void set(Temperature ) {
        this. = ;
    }

    public void set(Humidity ) {
        this. = ;
    }

    public void set(Pression ) {
        this. = ;
    }

    public void set(Temperature ) {
        this. = ;
    }

    public void set(Temperature ) {
        this. = ;
    }

    public void link(PlanetData _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Temperature _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Humidity _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Pression _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Temperature _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Temperature _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF2JEEP+ocjPaE= >>
    // ----------- >>
    public Weather() {
    // ----------- << method.body@AAAAAAF2JEEP+ocjPaE= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF19UPJ3IsVqWs= >>
// ----------- >>
}